### ISSUE TITLE
Possible null reference

### ISSUE THREAD

**Issue by thisbarker** [XamarinUniversity/AND205#1]
Could these lines throw a null reference exception if the fragment is not immediately used after construction?

https://github.com/XamarinUniversity/AND205/blob/33bddd6c18a0ac6cd76a6f8a8db1e3d968fd3aef/Exercise%203/Start/Clock/Clock/TimeFragment.cs#L33

https://github.com/XamarinUniversity/AND205/blob/master/Exercise%203/Completed/Clock/Clock/TimeFragment.cs#L33

**Comment by patridge** [comment]
I know it's been a while, but I just ran this exercise and tried to reproduce the null reference exception without any luck.

@thisbarker were you seeing a specific error here or just posing the question hypothetically? Given all the things on that line, a couple potential null references could happen. It could fire if the current activity is null, which would suggest the fragment outlived its parent activity, but I'm not certain the exact situation that would cause that. Feel free to re-open if you have more details. I'd love to make sure we get this addressed, if it's still got a problem.
